Repository unifiedjs/unified-engine, pull requests merged in 2020-03, with the labels that each got.

#44 Fix reconfiguring plugins
  lib/configuration.js
  package.json
  test/configuration-presets.js
  test/fixtures/config-plugins-basic-reconfigure/.foorc
  test/fixtures/config-plugins-basic-reconfigure/one.txt
  test/fixtures/config-plugins-basic-reconfigure/preset/index.js
  test/fixtures/config-plugins-basic-reconfigure/preset/plugin.js
  test/fixtures/config-plugins-reconfigure/.foorc
  test/fixtures/config-plugins-reconfigure/preset/array-to-object.js
  test/fixtures/config-plugins-reconfigure/preset/index.js
  test/fixtures/config-plugins-reconfigure/preset/merge-object.js
  test/fixtures/config-plugins-reconfigure/preset/object-to-array.js
  test/fixtures/config-plugins-reconfigure/preset/string-to-array.js
  test/fixtures/config-plugins-reconfigure/preset/string-to-object.js
  test/settings-and-plugins.js
Labels: 🐛 type/bug, 👶 semver/patch, 🗄 area/interface, 🙆 status/confirmed

#45 Fix to ignore non-text compilers
  lib/file-pipeline/stringify.js
  package.json
  test/fixtures/filled-file/one.txt
  test/output.js
Labels: 🐛 type/bug, 👶 semver/patch, 🗄 area/interface, 🙆 status/confirmed

#46 types: add typescript definitions for unified-engine
  package.json
  types/index.d.ts
  types/tsconfig.json
  types/tslint.json
  types/unified-engine-tests.ts
Labels: ☂️ area/types, 🔍 status/open, 🕸️ area/tests, 🦋 type/enhancement, 🧑 semver/major

#43 Add `ignorePathResolveFrom` option for reusable ignores
  doc/ignore.md
  doc/options.md
  lib/file-set-pipeline/file-system.js
  lib/finder.js
  lib/ignore.js
  lib/index.js
  package.json
  readme.md
  test/fixtures/sibling-ignore/deep/files/one.txt
  test/fixtures/sibling-ignore/deep/files/two.txt
  test/fixtures/sibling-ignore/deep/ignore
  test/fixtures/sibling-ignore/files/one.txt
  test/fixtures/sibling-ignore/files/two.txt
  test/ignore.js
  types/index.d.ts
Labels: 🗄 area/interface, 🙆 status/confirmed, 🦋 type/enhancement, 🧒 semver/minor
